name: Test On Release Created
on:
  release:
    types: [created, edited]
jobs:
  release:
    runs-on: ubuntu-latest
    container: cypress/included:9.4.1
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        run: |
          ./javascript/tradepanel/test/docker-run-test.sh
