name: Tradepanel - Test On Push
on:
  push:
    branches:
      - "**" # matches every branch
jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/included:9.4.1
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        run: |
          ./javascript/tradepanel/test/docker-run-test.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
